# gitlab-runner register 
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "hgw-poc-gitci"
  output_limit = 10000
  url = "https://git.digital.com/"
  token = "################"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0

[[runners]]
  name = "hgw-poc1-gitci"
  output_limit = 10000
  url = "https://git.digital.com/"
  token = "###############"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0

[[runners]]
  name = "hgw-device-manager"
  output_limit = 100000
  url = "https://git.digital.com/"
  token = "###############"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0

[[runners]]
  name = "hgw-core"
  output_limit = 100000
  url = "https://git.digital.com/"
  token = "############"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0

[[runners]]
  name = "hgw-integration"
  output_limit = 100000
  url = "https://git.digital.com/"
  token = "6YMcxzwC_vBzhvpsJ7ew"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0

[[runners]]
  name = "hgw-rule-manager"
  output_limit = 100000
  url = "https://git.digital.com/"
  token = "#############"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "maven:3.6-openjdk-8-slim"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/ubuntu/hgw_artifacts:/cache:rw", "/home/ubuntu/sonar_scanner:/tmp:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]
    shm_size = 0
