stages:
    - build-with-scan
    - check

build-with-scan:
    only:
      refs:
        - merge_requests
      variables:
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
        - $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"

    stage: build-with-scan
    script:
        - mvn -Dmaven.repo.local=/cache -f pom.xml clean install
        - /tmp/sonar-scanner-2.8/bin/sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=HGW-shared-device-manager-dev-eks-pipeline -Dsonar.projectName=HGW-shared-device-manager-dev-eks-pipeline -Dsonar.profile=homegateway -Dsonar.qualitygate=HGW-Dev-DM -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.java.libraries=/tmp/lombok-1.18.4.jar -Dsonar.exclusions=**/jacoco-resources/**,**/config/**,**/domain/**,**/domain/dto/**,**/config/**,**/exception/**,**/converter/**,**/hystrix-dashboard/**,**/turbine/**,**/constant/**,**/entity/**,**/*ContractVerifierTest.java,**/*Event_orchestratorTest.java -Dsonar.tests=. -Dsonar.junit.reportsPath=device-manager-core/target/surefire-reports -Dsonar.surefire.reportsPath=device-manager-adapter/target/surefire-reports,device-manager-core/target/surefire-reports,device-manager-deploy/target/surefire-reports,event-orchestrator-parent/event-orchestrator-core/target/surefire-reports,event-orchestrator-parent/event-orchestrator-adapter/target/surefire-reports -Dsonar.jacoco.reportPaths=device-manager-adapter/target/jacoco-output/merged.exec,device-manager-core/target/jacoco-output/merged.exec,device-manager-processor/target/jacoco-output/merged.exec,device-manager-deploy/target/jacoco-output/merged.exec,event-orchestrator-parent/event-orchestrator-core/target/jacoco-output/merged.exec,event-orchestrator-parent/event-orchestrator-adapter/target/jacoco-output/merged.exec -Dsonar.java.binaries=**/target/classes -Dsonar.java.coveragePlugin=jacoco -Dsonar.test.exclusions=**/src/main/java/** -Dsonar.test.inclusions=**/src/test/java/**
    artifacts:
        paths:
            - tmp/build

check:
    only:
      refs:
        - merge_requests
      variables:
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev"
        - $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
    stage: check
    script:
        - echo "this stage must run for all"
